[package]
name = "pg_anonymize"
version = "0.1.0"
authors = ["Koen Wilde <koen@chillheid.nl>"]
edition = "2018"

[dependencies]
structopt = "0.3"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
lipsum = "0.6"
